### ISSUE TITLE
Missing documentation about how to add Events, Flows, Decisions, Activities, Loops

### ISSUE THREAD

**Issue by garethloot** [mendix/ExtensionAPI-Samples#3]
I am missing a example of how i can add action steps like a create object or commit object to a microflow. What kind of types do you have to use in currentApp.Create<T>();

The examples show how to do a microflowCall but i want to use the build in action steps like retrieve create and decisions.

**Comment by ghost** [comment]
Hi Gareth, We currently don't support all model elements yet. 
For now, microflows only support call microflow actions and java actions. We will however soon be expanding this to more actions.

**Comment by garethloot** [comment]
Thanks, that explains it.
